import { Platform, StatusBar, StyleSheet } from "react-native";

export const HomeStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#fff" },
  headerContainer: { backgroundColor: "transparent" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 10,
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  headerLeft: { flexDirection: "row", alignItems: "center", flexShrink: 1 },
  headerRight: { flexDirection: "row", alignItems: "center" },
  customHeaderTitle: {
    fontSize: 19,
    color: "#1d2121",
    fontFamily: Platform.select({
      android: "Geist_700Bold",
      ios: "Geist_700Bold",
    }),
  },
  headerButton: { marginRight: 10, fontWeight: "bold" },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 20,
    marginVertical: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "#f0f0f0",
  },
  searchInput: { flex: 1, fontSize: 16 },
  contentRoot: { flex: 1, paddingHorizontal: 20 },
  scrollContent: { paddingTop: 10, paddingBottom: 40 },
  noteCard: {
    padding: 20,
    marginTop: 15,
    borderRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    minHeight: 80,
    borderWidth: 2,
    borderColor: "transparent",
  },
  selectedNote: { borderColor: "#C0392B", borderWidth: 2 },
  content: { fontSize: 20, flex: 1, marginRight: 10 },
  selectionIndicator: {
    width: 24,
    height: 24,
    marginLeft: 10,
    justifyContent: "center",
    alignItems: "center",
  },
});
